# Generated by Django 5.1.4 on 2024-12-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Firstname')),
                ('lastname', models.CharField(db_index=True, max_length=100, verbose_name='Lastname')),
                ('birthdate', models.DateField(blank=True, default=None, null=True, verbose_name='Birthdate')),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Gender')),
                ('tax_number', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Tax Number')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean13', models.CharField(default='', max_length=13, verbose_name='EAN-13')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default=None, max_length=20, null=True, verbose_name='Type')),
                ('street', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Street')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postcode', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Postcode')),
                ('region', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Region')),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['customer'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Customer')),
                ('product', models.ManyToManyField(default=None, to='shop.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['customer'],
            },
        ),
    ]
